version: "3"
services:
    db:
        image: mysql:5.7

        env_file:
            - conf.env
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
        networks:
            - app-network

        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

    server:
        build:
            context: node

        entrypoint: ["/var/tool/wait-for-it.sh", "db:3306", "--", "yarn", "run"]
        command: ["dev"]

        depends_on:
            - db

        privileged: true
        env_file:
            - conf.env

        volumes:
            - ../packages/:/var/app

        ports:
            - 8080:8080

        links:
            - db:db
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file:
            - conf.env
        ports:
            - 8081:80
        links:
            - db:db
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
